insert into user_model (email, nomeCompleto, senha) values ('a@a', 'tiburssin tiburssius', 'a');
insert into user_model (email, nomeCompleto, senha) values ('s@s', 'aroldo aroldus', 'a');
insert into user_model (email, nomeCompleto, senha) values ('d@d', 'cabral cabralzius', 'a');
insert into user_model (email, nomeCompleto, senha) values ('f@f', 'tonin toninhus', 'a');
insert into user_model (email, nomeCompleto, senha) values ('g@g', 'g g', 'a');

insert into question_model(question, answer, category, phase) values ('Feridas crônicas ocorrem quando, fisiologicamente, o processo de cicatrização não ocorre da forma esperada. Alguns autores indicam que toda ferida com mais de 5 dias é considerada uma lesão crônica.', false, 'Feridas crônicas', 1);
insert into question_model(question, answer, category, phase) values ('Feridas crônicas ocorrem quando, fisiologicamente, o processo de cicatrização não ocorre da forma esperada.', true, 'Feridas crônicas', 1);
insert into question_model(question, answer, category, phase) values ('Feridas agudas são aquelas em que a cicatrização ocorre dentro do período esperado e sem complicações.', true, 'Feridas agudas', 1);
insert into question_model(question, answer, category, phase) values ('eridas agudas são aquelas em que a cicatrização ocorre dentro do período esperado e sem complicações. Alguns autores indicam que toda ferida com mais de 20 dias é considerada uma lesão crônica.', false, 'Feridas agudas', 1);
insert into question_model(question, answer, category, phase) values ('Os fatores que afetam a cicatrização são estado nutricional, infecção, idade, medicamentos, tabagismo, unidade, cisalhamento e pressão.', true, 'Fatores que afetam a cicatrização', 1);
insert into question_model(question, answer, category, phase) values ('Os fatores que afetam a cicatrização são estado nutricional, infecção, idade, medicamentos, tabagismo, unidade, cisalhamento, pressão e fica no posição em pé por muito tempo.', false, 'Fatores que afetam a cicatrização', 1);
insert into question_model(question, answer, category, phase) values ('As feridas podem ser classificadas quanto ao agente causal como incisivas ou cirúrgicas e contusas, lacerantes e perfurantes.', true, 'Classificação das feridas', 1);
insert into question_model(question, answer, category, phase) values ('As características clínicas, especificando a sua localização, seu tamanho, característica da pele, quantidade de exsudato, odor, tipo de tecido presente na lesão.', false, 'Classificação das feridas', 1);
insert into question_model(question, answer, category, phase) values ('Os itens essenciais que devem ser avaliados em uma ferida são: tipo de lesão, localização da lesão, caracterização do leito da ferida, tipo e quantidade do exsudato, tamanho, profundidade e localização, características da margem da ferida, condição da pele perilesional, presença de túneis e/ou cavidades.', true, 'Itens essenciais que devem ser avaliados em uma ferida', 1);
insert into question_model(question, answer, category, phase) values ('Os itens essenciais que devem ser avaliados em uma ferida são: tipo de lesão, localização da lesão, caracterização do leito da ferida, tipo do exsudato, tamanho, profundidade e localização, características da margem da ferida.', false, 'Itens essenciais que devem ser avaliados em uma ferida', 1);
insert into question_model(question, answer, category, phase) values ('As características clínicas, especificando a sua localização, seu tamanho, característica da pele, quantidade de exsudato, odor, tipo de tecido presente na lesão, dor e os aspectos da pele peri lesão.', true, 'Itens que devem ser registrados na anotação de enfermagem', 1);
insert into question_model(question, answer, category, phase) values ('As feridas podem ser classificadas quanto ao grau de contaminação das feridas, podendo ser limpas, limpas-contaminadas e contaminadas.', false, 'Itens que devem ser registrados na anotação de enfermagem', 1);
insert into question_model(question, answer, category, phase) values ('Os tipos de exsudatos podem ser seroso, serossanguinolento, sanguinolento, purulento, amarelo, marrom ou verde.', true, 'Tipo do exsudato', 1);
insert into question_model(question, answer, category, phase) values ('Os tipos de exsudatos podem ser serossanguinolento, sanguinolento, purulento, amarelo, marrom ou verde.', false, 'Tipo do exsudato', 1);
insert into question_model(question, answer, category, phase) values ('São condições da pele perilesional que devem ser verificadas ao redor da ferida: maceração, vermelhidão, edema, calor e rubor.', true, 'Condições da pele perilesional', 1);
insert into question_model(question, answer, category, phase) values ('São condições da pele perilesional que devem ser verificadas ao redor da ferida: maceração, vermelhidão, edema e calor.', false, 'Condições da pele perilesional', 1);
insert into question_model(question, answer, category, phase) values ('Para mensuração da largura da ferida, o profissional deve utilizar uma régua limpa e descartável, medir o maior comprimento cefalocaudal (ou seja, de cima para baixo) da ferida, medir a maior largura perpendicular (90° em relação ao comprimento) da ferida. Essas medidas ajudam a determinar a área total da lesão.', true, 'Comprimento e largura da ferida', 1);
insert into question_model(question, answer, category, phase) values ('Para mensuração da largura da ferida, o profissional deve utilizar uma régua limpa e descartável, medir o maior comprimento cefalocaudal (ou seja, de baixo para cima) da ferida, medir a maior largura perpendicular (90° em relação ao comprimento) da ferida. Essas medidas ajudam a determinar a área total da lesão.', false, 'Comprimento e largura da ferida', 1);
insert into question_model(question, answer, category, phase) values ('Na avaliação dos pés dos pacientes, os profissionais devem verificar a pele dos pés em busca de qualquer alteração, como feridas, calosidades, bolhas ou áreas avermelhadas e fungos.', true, 'Avaliação dos pés em pacientes', 1);
insert into question_model(question, answer, category, phase) values ('Na avaliação dos pés dos pacientes não é necessário que o profissional avalie as áreas de maior pressão, como calcanhares e região plantar.', false, 'Avaliação dos pés em pacientes', 1);
insert into question_model(question, answer, category, phase) values ('Na avaliação dos pés dos pacientes, os profissionais devem verificar a presença de deformidades nos pés, como dedos em garra, proeminências de metatarsos ou alterações articulares.', true, 'Avaliação dos pés em pacientes', 1);
insert into question_model(question, answer, category, phase) values ('Na avaliação dos pés em pacientes, os profissionais devem avaliar os pulsos pediosos e tibiais posteriores. A ausência de pulsos pode indicar doença vascular periférica.', true, 'Avaliação dos pés em pacientes', 1);
insert into question_model(question, answer, category, phase) values ('Não é necessário avaliar a sensibilidade dos pés utilizando o teste de monofilamento de 20g (para sensibilidade tátil).', false, 'Avaliação dos pés em pacientes', 1);
insert into question_model(question, answer, category, phase) values ('Não é necessário avaliar a sensibilidade dos pés utilizando o teste de diapasão de 140 Hz (para sensibilidade vibratória).', false, 'Avaliação dos pés em pacientes', 1);
insert into question_model(question, answer, category, phase) values ('Não é necessário avaliar a sensibilidade dos pés utilizando o teste de pino ou palito (para sensibilidade dolorosa).', true, 'Avaliação dos pés em pacientes', 1);
insert into question_model(question, answer, category, phase) values ('Não é necessário avaliar a sensibilidade dos pés utilizando o teste de martelo (para reflexo aquileu).', true, 'Avaliação dos pés em pacientes', 1);
insert into question_model(question, answer, category, phase) values ('A mensuração da profundidade da ferida pode ser obtida introduzindo uma espátula estéril ou seringa de insulina sem agulha no ponto mais profundo da lesão. Na altura da borda da ferida mais próxima ao local onde está inserida a seringa, marca-se o ponto correspondente à altura, na espátula ou seringa.', true, 'Mensuração de ferida', 1);
insert into question_model(question, answer, category, phase) values ('A mensuração da profundidade da ferida pode ser obtida introduzindo uma espátula estéril ou seringa de insulina sem agulha no ponto mais profundo da lesão. Na altura da margem da ferida mais próxima ao local onde está inserida a seringa, marca-se o ponto correspondente à altura, na espátula ou seringa.', false, 'Mensuração de ferida', 1);
insert into question_model(question, answer, category, phase) values ('O tecido de granulação é uma estrutura formada durante o processo de cicatrização de feridas. Ele é composto por células especializadas, como fibroblastos, macrófagos e células endoteliais, além de uma matriz extracelular rica em colágeno.', true, 'Definição de tecido de granulação', 2);
insert into question_model(question, answer, category, phase) values ('O tecido de granulação inviável é caracterizado por apresentar uma coloração avermelhada ou rosada, devido à presença de vasos sanguíneos recém-formados.', false, 'Definição de tecido de granulação', 2);
insert into question_model(question, answer, category, phase) values ('Necrose indica morte celular ou de tecidos no organismo. Sabe-se que o processo de necrose envolve também o processo inflamatório no local. Várias são as causas de necrose, entre elas, diminuição do aporte de sangue ou falta de oxigenação com a presença de toxinas e enzimas que levam à morte celular.', true, 'Definição de tecido necrosado', 2);
insert into question_model(question, answer, category, phase) values ('Necrose indica morte celular ou de tecidos no organismo. Sabe-se que o processo de necrose envolve também o processo inflamatório, fibroblastos, macrófagos e células endoteliais no local. Várias são as causas de necrose, entre elas, diminuição do aporte de sangue ou falta de oxigenação com a presença de toxinas e enzimas que levam à morte celular.', false, 'Definição de tecido necrosado', 2);
INSERT INTO question_model (question, answer, category, phase)
VALUES ('Desbridamento é o processo de remoção de tecido necrótico ou materiais biológicos de uma lesão, com o objetivo de expor o tecido saudável e promover a cicatrização.', true, 'Definição de desbridamento', 2),
       ('Desbridamento não é o processo de remoção de tecido necrótico ou materiais biológicos de uma lesão, com o objetivo de expor o tecido saudável e promover a cicatrização.', false, 'Definição de desbridamento', 2),
       ('Os tipos de desbridamento são autolítico, mecânico, instrumental e enzimático.', true, 'Tipo de desbridamento', 2),
       ('Os tipos de desbridamento são auto mecânico, mecânico, instrumental e enzimático.', false, 'Tipo de desbridamento', 2),
       ('Desbridamento autolítico promove a manutenção de um leito úmido e em temperatura em torno de 37°C a fim de atrair neutrófilos e macrófagos para a lesão, os quais irão liberar enzimas lisossomais para digerir os detritos. Proporciona maior lise e fagocitose do tecido necrótico, do qual deriva o nome autólise – que significa a autodestruição.', true, 'Definição de desbridamento autolítico', 2),
       ('Desbridamento autolítico promove a manutenção de um leito úmido e em temperatura em torno de 38°C a fim de atrair neutrófilos e macrófagos para a lesão, os quais irão liberar enzimas lisossomais para digerir os detritos. Proporciona maior lise e fagocitose do tecido necrótico, do qual deriva o nome autólise – que significa a autodestruição.', false, 'Definição de desbridamento autolítico', 2),
       ('No desbridamento mecânico, retiram-se sujidades, corpo estranho e o tecido inviável.', true, 'Definição de desbridamento mecânico', 2),
       ('No desbridamento mecânico, o profissional não utiliza a força física para a remoção da necrose.', false, 'Definição de desbridamento mecânico', 2),
       ('O desbridamento enzimático atua com a ação da enzima (mais comuns a colagenase clostridiopeptidase, bromalina e papaína) quebrando as fibras de colágeno que unem o tecido necrosado ou esfacelado ao leito da ferida.', true, 'Definição de desbridamento enzimático', 2),
       ('Os tipos de coberturas que promovem desbridamento autolítico são hidrogel e hidrocoloide.', true, 'Tipo de cobertura que promove desbridamento autolítico', 2),
       ('Os tipos de coberturas que promovem desbridamento autolítico são hidrogel, papaína e hidrocoloide.', false, 'Tipo de cobertura que promove desbridamento autolítico', 2),
       ('Os tipos de coberturas que promovem o desbridamento enzimático são papaína, colagenase, fibrinolisina ou plasmina.', true, 'Tipo de cobertura que promove desbridamento enzimático', 2),
       ('Os tipos de coberturas que promovem o desbridamento enzimático são papaína 4 a 10%, colagenase, fibrinolisina ou plasmina.', false, 'Tipo de cobertura que promove desbridamento enzimático', 2),
       ('As medidas preventivas à úlcera venosa são a terapia compressiva com meias, bandagens ou sistemas de compressão elásticos.', true, 'Medidas preventivas à úlcera venosa', 3),
       ('As medidas preventivas à úlcera venosa são a terapia compressiva com meias, bandagem e bota de unna.', false, 'Medidas preventivas à úlcera venosa', 3);
INSERT INTO question_model (question, answer, category, phase)
VALUES
('Uso da cobertura primária conforme avaliação do profissional e uso da terapia compressiva (elástica, inelástica ou múltiplas camadas).', true, 'Condutas para tratar úlcera venosa', 3),
('Uso da terapia compressiva (elástica, inelástica ou múltiplas camadas).', false, 'Condutas para tratar úlcera venosa', 3),
('Avaliação de risco, utilizando uma escala, uso de superfícies de suporte, posicionamento e mudança de posição conforme avaliação clínica do profissional, hidratação da pele e nutrição.', true, 'Medidas preventivas para lesão por pressão', 3),
('Avaliação de risco, utilizando uma escala, uso de superfícies de suporte, posicionamento e mudança de posição a cada 3 horas, hidratação e nutrição.', false, 'Medidas preventivas para lesão por pressão', 3),
('Avaliação diária da pele, limpeza suave da pele utilizando sabão neutro, uso de cremes ou pomadas de barreira para proteger a pele contra a umidade, uso de fraldas ou absorventes adequados para manter a pele seca e evitar produtos que contenham álcool ou fragrâncias.', true, 'Medidas preventivas ao desenvolvimento da dermatite associada à incontinência', 3),
('Avaliação diária da pele, limpeza suave da pele utilizando sabão ou sabonete líquido, uso de cremes ou pomadas de barreira para proteger a pele contra a umidade, uso de fraldas ou absorventes adequados para manter a pele seca e evitar produtos que contenham álcool ou fragrâncias.', false, 'Medidas preventivas ao desenvolvimento da dermatite associada à incontinência', 3),
('A escolha do curativo deve ser baseada em evidências científicas, conhecimento técnico e avaliação clínica. É necessário consultar protocolos institucionais, para verificar quais são as coberturas padronizadas na instituição.', true, 'Escolha do curativo', 3),
('A escolha do curativo deve ser baseada em evidências científicas, conhecimento técnico e avaliação clínica. Não é necessário consultar protocolos institucionais.', false, 'Escolha do curativo', 3),
('Estão relacionados ao tipo de cobertura para tratar lesão com tecido de granulação sem exsudato: hidrocolóides ou placas, hidrogel, gazes com petrolato, papaína 2 %, polihexanida (PHMB) e betaína.', true, 'Tipo de cobertura para lesão com tecido de granulação sem exsudato', 3),
('Estão relacionados ao tipo de cobertura para tratar lesão com tecido de granulação sem exsudato: hidrocolóides ou placas, hidrogel, rayon úmido com soro fisiológico e papaína 10%.', false, 'Tipo de cobertura para lesão com tecido de granulação sem exsudato', 3),
('Estão relacionados ao tipo de cobertura para tratar lesão com tecido de granulação com grande quantidade de exsudato purulento: alginato com prata, carvão ativado e hidrofibra com prata.', true, 'Tipo de cobertura para lesão com tecido de granulação com grande quantidade de exsudato purulento', 3),
('Estão relacionados ao tipo de cobertura para tratar lesão com tecido de granulação com grande quantidade de exsudato purulento: hidrogel com prata, hidrocolóide com prata, polihexanida (PHMB) e betaína.', false, 'Tipo de cobertura para lesão com tecido de granulação com grande quantidade de exsudato purulento', 3),
('Alginato de cálcio e sódio possui um alto poder de absorção, que auxilia o desbridamento enzimático e autolítico e absorve o excesso de exsudato. É indicado para ferida exsudativas, com sangramento.', true, 'Alginato de Cálcio e Sódio', 3),
('Alginato de cálcio e sódio possui um alto poder de absorção, que auxilia o desbridamento autolítico e absorve o excesso de exsudato. É indicado para ferida exsudativas, com sangramento.', false, 'Alginato de Cálcio e Sódio', 3),
('A hidrofibra com prata mata uma ampla quantidade de bactérias, incluindo superbactérias resistentes aos antibióticos, com seu reservatório de prata. Evita formação de biofilme. Tira o excesso de exsudato, ajuda a evitar contaminação cruzada e previne maceração. Mantém a umidade ideal para a ferida. Camada ocupa os espaços da ferida e mantém a umidade ideal, eliminando espaço para tecido morto e proliferação das bactérias.', true, 'Hidrofibra com prata', 3),
('A hidrofibra com prata mata uma ampla quantidade de bactérias, incluindo superbactérias resistentes aos antibióticos, com seu reservatório de prata. Não contribui para prevenção do biofilme. Tira o excesso de exsudato, ajuda a evitar contaminação cruzada e previne maceração. Mantém a umidade ideal para a ferida. Camada ocupa os espaços da ferida e mantém a umidade ideal, eliminando espaço para tecido morto e proliferação das bactérias.', false, 'Hidrofibra com prata', 3),
('As gazes com petrolatum são constituídas de malha (gazes) não aderente (não gruda na ferida) e embebida com óleo de petrolatum. São indicadas para peles descamativas, vulneráveis a lesões, com lesões superficiais como queimaduras, lesões por pressão (úlceras), lacerações e outras lesões em que o curativo não possa aderir à lesão.', true, 'Gazes com petrolatum', 3),
('As gazes com petrolatum são constituídas de malha (gazes) não aderente (não gruda na ferida) e embebida com ácido graxo essencial. São indicadas para peles descamativas, vulneráveis a lesões, com lesões superficiais como queimaduras, lesões por pressão (úlceras), lacerações e outras lesões em que o curativo não possa aderir à lesão.', false, 'Gazes com petrolatum', 3);

insert into game (status, nivelAtual, usuarioID, numeroAcertos, numeroErros, dataDeCriacao) VALUES ('pendente',5,5,200,0,'25/10/2025');
insert into game (status,nivelAtual, usuarioID, numeroAcertos, numeroErros, dataDeCriacao) VALUES ('pendente',1,2,20,10,'20/10/2021');
insert into game (status,nivelAtual, usuarioID, numeroAcertos, numeroErros, dataDeCriacao) VALUES ('pendente',1,6,60,10,'20/10/2021');
insert into game (status, nivelAtual, usuarioID, numeroAcertos, numeroErros, dataDeCriacao) VALUES ('pendente',2,3,50,2,'1/10/2021');
insert into game (status, nivelAtual, usuarioID, numeroAcertos, numeroErros, dataDeCriacao) VALUES ('pendente',5,3,100,0,'25/10/2025');

